### ISSUE TITLE
Please provide CookCLI for Linux arm64

### ISSUE THREAD

**Issue by Lonerider2010** [cooklang/cookcli#40] opened 2022-02-21 22:50 UTC
... as I would like to use it on this platform.
Thanks a lot.

**Comment by Lonerider2010** [comment] 2022-02-24 23:28
Can I read your "thumbs up" as a consent? If so, do you have plans when to implement it?

**Comment by dubadub** [comment] 2022-02-26 10:43
Yep, I added an experimental build to the latest release https://github.com/cooklang/CookCLI/releases/tag/v0.1.3, could you please check if it's working? If yes, I update the release flow.

**Comment by Lonerider2010** [comment] 2022-02-26 21:22
Ok, lets check:
- [ ] cook recipe read
- [ ] cook recipe read --output-format
- [ ] cook recipe read --only-ingredients
- [ ] cook shopping-list: Speicherzugriffsfehler (segmentation fault?)
- [ ] cook server: Speicherzugriffsfehler (segmentation fault?)
- [ ] cook seed
- [ ] cook version

**Comment by dubadub** [comment] 2022-02-28 19:40
Thanks for checking @Lonerider2010. It might be related to `glibc` bug mentioned in https://github.com/cooklang/CookCLI/issues/39 and https://github.com/cooklang/CookCLI/issues/29. I don't have a solution yet.

**Comment by dubadub** [comment] 2022-03-12 21:36
@Lonerider2010 I think I found a workaround and this issue is fixed in `v0.1.4`.

**Comment by Lonerider2010** [comment] 2022-03-12 23:27
@dubadub, thank you for the new version. As you can see in my checklist above, the shopping-list is ok now and ready for the next shopping ;-)
With the server, things are not as well. When I start `cook server <dir-path>`, I can start the web page on my browser.
There I can see the home page, but neither the sub-directories of `<dir-path>`, nor the `.cook` files within this structure.
Even more, if I try to click around, `cook` crashes again with the Speicherzugriffsfehler (segmentation fault?).
My impression is that `cook` is able to start the server and show the static parts of the web page, but is not able to fill in the dynamic parts like the sub-directories or a list of the `.cook` files.

**Comment by dubadub** [comment] 2022-03-13 10:04
I don't have disposable Raspberry Pi at hand and use a Docker image with Ubuntu 20.04.4 aarch64 (kernel 5.10.47-linuxkit). I'm not able to reproduce the issue you have. What I did:

    cd /tmp
    mkdir server-test
    cd server-test
    cook seed
    cook server

After that I can open http://127.0.0.1:9080 and navigate without any issues. Could you please try this as well? So we can eliminate any potential issues with recipe files?

**Comment by Lonerider2010** [comment] 2022-03-13 21:51
@dubadub, now I followed your instructions, but with the same result as with my environment. So obviously it does not depend on my recipe files. Just to mention: these files are ok for 
- the other functions of cookCLI (see my checklist above)
- CookVSCode
- Obsidian Cooklang Editor
- cooklang-parser

My question: is there a kind of debug mode available for CookCLI? Can I produce a debug log that would help you to find the problem and hopefully solve it?

**Comment by dubadub** [comment] 2023-11-30 17:23
With migration CLI to Rust and now we have an ARM version as well. One can download binary from [the releases](https://github.com/cooklang/cookcli/releases).

**Closed by dubadub** 2023-11-30 17:23 UTC
Labels: bug, enhancement
